# Site
name: 'Raghav Sikaria'
description: 'to serve as my portfolio and personal blog site'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'thepiranha'
formspree: https://formspree.io/f/xdojakel
google_analytics: UA-165339475-1
email: 'raghavsikaria9@gmail.com'
github_link: 'https://github.com/raghavsikaria'
linkedin_link: 'https://www.linkedin.com/in/raghavsikaria/'
instagram_link: 'https://www.instagram.com/subah_ka_bhoola/?igshid=YmMyMTA2M2Y%3D'
stackoverflow_link: 'https://stackoverflow.com/users/7890913/raghavsikaria'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]